baseURL: https://sophie-touami-website.netlify.app/
languageCode: en-us
title: Sophie Touami's website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Student in the Masters in Financial Analysis at London Business School
    title: Hi, my name is Sophie Touami
  blog: {Sophie Touami: Student of the LBS, lokking for opportunities in IBD}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Sussex Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: stouami.mfa222@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+352) 661635165
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Sophie Touami
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: #
      - icon: fa-facebook
        label: Facebook
        url: #
      - icon: fa-instagram
        label: Instagram
        url: #
      - icon: fa-github
        label: GitHub
        url: https://github.com/So-tou
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sophietouami/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: Who I am
      - name: Generic Blog
        url: My resume
      - name: Elements
        url: My projects
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Double degree bachelor and Masters in Finance
        title: Academic experience
        url: blogs/aliquam
      - image: work.jpg
        subtitle: my resume
        title: Working experience
        url: blogs/tempus
      - image: skills.jpg
        subtitle: Positive, multi-linguistics, hardworking
        title: Skills
        url: blogs/magna
      - image: volunteer.jpg
        subtitle: REFM - MEC
        title: Volunteering
        url: blogs/ipsum
      - image: pic02.jpg
        subtitle: Discover my past trips
        title: Travel
        url: blogs/ipsum
      - image: hobbies.jpg
        subtitle: Learn more about what I like
        title: Hobbies
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Before joining the prestigious London Business School, I graduated from a dual bachelor degree in Business Administration and International Mangement.
      \n    I studied at NEOMA Business School in France and I studied in the University of International Business and Economics in Beijing, China. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: A Motivated and Hardworking student
    url: blogs
