baseURL: https://sophie-touami-website.netlify.app/
languageCode: en-us
title: Sophie Touami's website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Student in the Masters in Financial Analysis at London Business School
    title: Sophie Touami's website
  blog: {Sophie Touami: Student of the LBS, lokking for opportunities in IBD}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Sussex Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: stouami.mfa222@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+352) 661635165
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Sophie Touami
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: #
        label: Twitter
        url: #
      - icon: #
        label: Facebook
        url: #
      - icon: #
        label: Instagram
        url: #
      - icon: fa-github
        label: GitHub
        url: https://github.com/So-tou
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sophietouami/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: My Resume 
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: Who I am
      - name: #
        url: #
      - name: #
        url: My projects
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Double degree bachelor and Masters in Finance
        title: Academic experience
        url: blogs/academicexperience
      - image: work.jpg
        subtitle: my resume
        title: Working experience
        url: blogs/workingexperience
      - image: pic02.jpg
        subtitle: Discover worldwide trips
        title: Travel
        url: blogs/magna
      - image: volunteer.jpg
        subtitle: REFM - MEC
        title: Volunteering
        url: blog1.md

  two:
    buttonText: My resume
    enable: yes
    subtitle: "I studied half of my undergraduate studies in Mandarin in Beijing.
      \n    I even undertook courses designed for Chinese native speakers and I passed thanks to my hardwork. \n    After my graduation,
      I found a full-time position, as a fund accountant (speicalised in private equity, real estate, securities), in Luxembourg, at the height of the pandemic. Last August, I joined the Masters in Financial Analysis programme at London Business School. 
      \n    I am currently looking for a summer internship in Investment banking division.
      \n    For further information, please click on the below button to find my resume.
      ."
    title: A Motivated and Hardworking student
    url: blogs
